server:
  port: 9999
spring:
  main:
    #web-application-type: none
    banner-mode: console
  jpa:
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        #hbm2ddl.import_files: classpath:/init.sql
    database-platform: org.hibernate.dialect.H2Dialect
    #database: H2
  datasource:
    #platform: h2
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    #continue-on-error: true
    data: classpath:/init.sql
  h2:
      console:
        enabled: true
        path: /console
        settings:
          trace: false
          web-allow-others: false
logging:
  config: classpath:logback.xml
  
  
 #spring.jpa.properties.hibernate.hbm2ddl.import_files=i