spring:
  main:
    banner-mode: console
  jpa:
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    data: classpath:/init.sql
logging:
  config: classpath:logback.xml
